"""
JSON-based storage for scheduler configuration.

Persists scheduler settings including enabled status, schedule times,
and statistics.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Dict, Any
from threading import Lock

import config


class SchedulerStorage:
    """Thread-safe JSON storage for scheduler configuration."""
    
    def __init__(self, storage_path: Optional[Path] = None):
        """
        Initialize scheduler storage.
        
        Args:
            storage_path: Path to JSON file. Defaults to {TEMP_VIDEOS_DIR}/scheduler_config.json
        """
        self.storage_path = storage_path or config.TEMP_VIDEOS_DIR / "scheduler_config.json"
        self._lock = Lock()
        self._ensure_storage_exists()
    
    def _ensure_storage_exists(self) -> None:
        """Create storage file with default configuration if it doesn't exist."""
        if not self.storage_path.exists():
            self.storage_path.parent.mkdir(parents=True, exist_ok=True)
            default_config = {
                'enabled': True,
                'schedule_times': ['12:00', '19:00'],
                'use_saved_ideas': False,
                'idea_id': None,
                'total_videos_generated': 0,
                'last_run': None
            }
            self._write_data(default_config)
    
    def _read_data(self) -> Dict[str, Any]:
        """Read scheduler configuration from storage."""
        with self._lock:
            try:
                with open(self.storage_path, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except (json.JSONDecodeError, FileNotFoundError):
                return {
                    'enabled': True,
                    'schedule_times': ['12:00', '19:00'],
                    'use_saved_ideas': False,
                    'idea_id': None,
                    'total_videos_generated': 0,
                    'last_run': None
                }
    
    def _write_data(self, data: Dict[str, Any]) -> None:
        """Write scheduler configuration to storage."""
        with self._lock:
            with open(self.storage_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
    
    def get_config(self) -> Dict[str, Any]:
        """
        Get current scheduler configuration.
        
        Returns:
            Scheduler configuration dict
        """
        return self._read_data()
    
    def update_config(self, enabled: Optional[bool] = None,
                     schedule_times: Optional[List[str]] = None,
                     use_saved_ideas: Optional[bool] = None,
                     idea_id: Optional[str] = None) -> Dict[str, Any]:
        """
        Update scheduler configuration.
        
        Args:
            enabled: Enable/disable scheduler
            schedule_times: List of times in HH:MM format
            use_saved_ideas: Whether to use saved ideas
            idea_id: Specific idea ID to use
            
        Returns:
            Updated configuration
        """
        config = self._read_data()
        
        if enabled is not None:
            config['enabled'] = enabled
        if schedule_times is not None:
            config['schedule_times'] = schedule_times
        if use_saved_ideas is not None:
            config['use_saved_ideas'] = use_saved_ideas
        if idea_id is not None:
            config['idea_id'] = idea_id
        
        self._write_data(config)
        return config
    
    def record_run(self) -> None:
        """Record a successful scheduler run."""
        config = self._read_data()
        config['last_run'] = datetime.now().isoformat()
        config['total_videos_generated'] = config.get('total_videos_generated', 0) + 1
        self._write_data(config)
    
    def get_last_run(self) -> Optional[str]:
        """
        Get timestamp of last scheduler run.
        
        Returns:
            ISO format timestamp or None
        """
        config = self._read_data()
        return config.get('last_run')
    
    def get_total_videos(self) -> int:
        """
        Get total number of videos generated by scheduler.
        
        Returns:
            Video count
        """
        config = self._read_data()
        return config.get('total_videos_generated', 0)
