"""Pydantic models for scheduler configuration."""

from typing import List, Optional
from pydantic import BaseModel, Field, validator


class ScheduleTime(BaseModel):
    """Model for a scheduled time."""
    hour: int = Field(..., ge=0, le=23, description="Hour in 24h format")
    minute: int = Field(..., ge=0, le=59, description="Minute")

    def to_time_string(self) -> str:
        """Convert to HH:MM format."""
        return f"{self.hour:02d}:{self.minute:02d}"


class SchedulerConfig(BaseModel):
    """Request model for configuring the scheduler."""
    enabled: bool = Field(
        default=True,
        description="Whether the scheduler is enabled"
    )
    schedule_times: List[ScheduleTime] = Field(
        ...,
        description="List of times to generate videos",
        min_items=1,
        example=[
            {"hour": 12, "minute": 0},
            {"hour": 19, "minute": 0}
        ]
    )
    use_saved_ideas: bool = Field(
        default=False,
        description="Whether to use saved ideas for generation"
    )
    idea_id: Optional[str] = Field(
        default=None,
        description="Specific idea ID to use (if use_saved_ideas is True)"
    )

    @validator('schedule_times')
    def validate_unique_times(cls, v):
        """Ensure schedule times are unique."""
        time_strings = [t.to_time_string() for t in v]
        if len(time_strings) != len(set(time_strings)):
            raise ValueError("Schedule times must be unique")
        return v


class SchedulerStatus(BaseModel):
    """Response model for scheduler status."""
    enabled: bool
    running: bool
    schedule_times: List[str] = Field(
        description="List of scheduled times in HH:MM format"
    )
    next_run: Optional[str] = Field(
        default=None,
        description="Next scheduled run time (ISO format)"
    )
    last_run: Optional[str] = Field(
        default=None,
        description="Last run time (ISO format)"
    )
    total_videos_generated: int = Field(
        default=0,
        description="Total videos generated by scheduler"
    )
    use_saved_ideas: bool
    current_idea_id: Optional[str] = None
